repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.2
    hooks:
      - id: ruff-check
        name: ruff-check-phased
        args:
          - --fix
          - --no-cache
          - config
          - common
          - producers
          - consumers
          - test
        pass_filenames: false
      - id: ruff-format
        name: ruff-format-phased
        args:
          - config
          - common
          - producers
          - consumers
          - test
        pass_filenames: false
